language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - pypy

before_install:
  - git submodule update --init --recursive
  - git clone git://github.com/maxmind/libmaxminddb
  - cd libmaxminddb
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script:
  - CFLAGS="-Werror -Wall -Wextra" python setup.py test
  - MAXMINDDB_PURE_PYTHON=1 python setup.py test
  - if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then pylint maxminddb; fi

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
